const ACTIONS = {
  SET_LOADING: 'SET_LOADING',
  SET_SEARCH_CRITERIA: 'SET_SEARCH_CRITERIA',
  SET_SEARCH_OPTIONS: 'SET_SEARCH_OPTIONS',
  SET_PHOTOS: 'SET_PHOTOS',
  SET_SELECTED_PHOTO_ID: 'SET_SELECTED_PHOTO_ID',
  SET_ERROR: 'SET_ERROR',
};

export default ACTIONS;